name: weather_http
version: 0.0.1
publish_to: 'none' 

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  http: 1.2.1
  weather_core: 
    path: ../weather_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.0
  dart_code_metrics_presets: 2.10.0
