name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  weather_core:
    path: ../weather_core
  weather_http:
    path: ../weather_http
  weather_ui_core:
    path: ../weather_ui_core

  get_it: 7.6.7
  provider: 6.1.2

  mobx: 2.3.3+2
  flutter_mobx: 2.2.1+1

  http: 1.2.1
  http_interceptor: 2.0.0-beta.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.0
  dart_code_metrics_presets: 2.10.0
  build_runner: 2.4.9
  mobx_codegen: 2.6.1

flutter:
  uses-material-design: true
  fonts:
    - family: SFUIText
      fonts:
        - asset: packages/weather_ui_core/fonts/SFUIText-Bold.ttf
          weight: 700
        - asset: packages/weather_ui_core/fonts/SFUIText-Heavy.ttf
          weight: 800
        - asset: packages/weather_ui_core/fonts/SFUIText-Semibold.ttf
          weight: 600
        - asset: packages/weather_ui_core/fonts/SFUIText-Medium.ttf
          weight: 500
        - asset: packages/weather_ui_core/fonts/SFUIText-Regular.ttf
          weight: 400
          style: normal
        - asset: packages/weather_ui_core/fonts/SFUIText-Light.ttf
          weight: 300
        - asset: packages/weather_ui_core/fonts/SFUIText-UltraLight.ttf
          weight: 200
