name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get_it: 7.6.7
  provider: 6.1.2

  mobx: 2.3.3+2
  flutter_mobx: 2.2.1+1

  http: 1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.0
  dart_code_metrics_presets: 2.10.0
  build_runner: 2.4.9
  mobx_codegen: 2.6.1

flutter:
  uses-material-design: true
